language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.1.4
script: 'bundle exec rake test'
notifications:
  recipients:
    - jonah@pixelhipsters.com
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rubyonadhd"
